#!/usr/bin/env python2

import os
import struct
import random
import shutil
import subprocess
import sys
from intelhex import IntelHex
from Crypto.Cipher import AES
from Crypto.Random.random import StrongRandom

def CMACHash(key,inBytes):
    encryptor = AES.new(key,AES.MODE_CBC,b'\x00'*16,segment_size=128)
    if len(inBytes) % 16 != 0:
        block = inBytes + b'\x00'*(len(inBytes)%16)
    else:
        block = inBytes
    output = (encryptor.encrypt(block))
    return output[-16:]

def bytesToHexList(data):
    #data_new = ["{:x}".format(x) for x in data]
    data_new = ["{:02x}".format(ord(x)) for x in data]
    return ["\\x{}".format(b) for b in data_new]

def bytesToCString(data):
    return "".join(bytesToHexList(data))

def generate128Entropy():
    return os.urandom(16) 

def generate256Entropy():
    return os.urandom(32) 

FILE_DIR = os.path.abspath(os.path.dirname(__file__))

def make_bootloader(password=None):
    """Build the bootloader from source.
    Return:
        True if successful, False otherwise.
    """
    # Change into directory containing bootloader.
    os.chdir('../bootloader')

    subprocess.call('make clean', shell=True)
    # Call make in subprocess to build bootloader.
    if password is not None:
        status = subprocess.call('make PASSWORD="%s"' % password, shell=True)
    else:
        status = subprocess.call('make')

    # Return True if make returned 0, otherwise return False.
    return (status == 0)

def copy_artifacts():
    """Copy bootloader build artifacts into the host tools directory.
    """
    # Get directory containing this file (host_tools).
    dst_dir = FILE_DIR

    # Get directory containing bootloader output (bootloader).
    src_dir = os.path.join(os.path.dirname(dst_dir), 'bootloader')

    # Copy build artifacts from bootloader directory.
    shutil.copy(os.path.join(src_dir, 'flash.hex'), dst_dir)
    shutil.copy(os.path.join(src_dir, 'eeprom.hex'), dst_dir)
    shutil.copy(os.path.join(dst_dir, 'hfuse.hex'), src_dir)
    shutil.copy(os.path.join(dst_dir, 'lfuse.hex'), src_dir)
    shutil.copy(os.path.join(dst_dir, 'efuse.hex'), src_dir)
    shutil.copy(os.path.join(dst_dir, 'lock.hex'), src_dir)

def write_fuse_file(fuse_name, fuse_value):
    hex_file = IntelHex()
    hex_file[0] = fuse_value

    with open(os.path.join(FILE_DIR, fuse_name + '.hex'), 'wb+') as outfile:
        hex_file.tofile(outfile, format='hex')

def expandNibble(nibble):
    expandedNibble = 0
    for i in range(4):
        iBit = nibble & (1 << i)
        if iBit != 0:
            expandedNibble += 2**(2*i+1)
        else:
            expandedNibble += 2**(2*i)
    return struct.pack(">B",expandedNibble)

def generateMaskedMirror(binaryString):
    resultant = b''
    # Expand each byte to be an equal number of 1s and 0s
    for char in binaryString:
        # Convert characters to ints
        byteVal = ord(char)
        lower = byteVal & (2**4 - 1)
        upper = byteVal >> 4
        resultant += expandNibble(upper) + expandNibble(lower)
    return resultant

def generate_secrets():
    """Generate the keys and Password.
    """
    FW_KEY = generate256Entropy()
    RB_KEY = generate256Entropy()
    H_KEY = generate256Entropy()
    RBH_KEY = generate256Entropy()
    VERIFY_KEY = generate256Entropy()
    FW_IV = generate128Entropy()
    RB_IV = generate128Entropy()
    RB_PW = os.urandom(24)
    RAND_SEED = os.urandom(2)
    all_keys_and_ivs = [("FW_KEY", FW_KEY),
                    ("RB_KEY",RB_KEY),
                    ("H_KEY", H_KEY),
                    ("FW_IV", FW_IV),
                    ("RB_IV",RB_IV),
                    ("RBH_KEY",RBH_KEY),
                    ("VERIFY_KEY",VERIFY_KEY),
                    ("RB_PW",RB_PW),
                    ("RAND_SEED",RAND_SEED)]
    return all_keys_and_ivs

def make_secrets_file(secrets,secret_file):
    """Construct secret_build_output.txt with all of the necessary keys and
    passwords.
    """
    for data in secrets:
        if "KEY" in data[0] or "PW" in data[0]:
            secret_file.write("#define " + data[0] + " \"" + 
                bytesToCString(generateMaskedMirror(data[1]))+'\"\n' +
                "#define PC_" + data[0] + " \"" + 
                bytesToCString(data[1]) + "\"\n")
        else:
            secret_file.write("#define " + data[0] + " \"" +
                bytesToCString(data[1]) + "\"\n")
	

def stripLine(intelLine):
    """Pulls the data out of a line of Intel hex and packs it as bytes.
    """
    intLine = intelLine[9:-3]
    if len(intLine) == 0:
        return b'' 
    # if it is a data line
    if intelLine[7:9] == "00":
        final = b'' 
        for i in range(len(intLine)//2):
            final += struct.pack(">B",int(intLine[(2*i):(2*i+2)],16))
        return struct.pack(">{}s".format(len(intLine)//2),final)
    # if it is not a data line
    else:
        return b''

def addrOf(intHexLine):
    """Extract the address bytes from an intel hex line.
    """
    return int(intHexLine[3:7],16)

def dataLen(intHexLine):
    """Extract the length of the true data section to be safe.
    """
    return len(intHexLine[9:-3])//2

def genMem(intHex):
    with open(intHex,'r') as hexFile:
        dump = []
        for currentLine in hexFile:
            recordType = currentLine[7:9]
            if recordType == '00':
                # If the last line is now continuos append it's data as is
                dump.append(stripLine(currentLine))
                # Initialize values for previous line as current line
            prevLine = currentLine
        return b''.join(dump)

if __name__ == '__main__':
    secrets = generate_secrets()
    with open('../bootloader/secret_build_output.txt', 'w') as secret_file:
        make_secrets_file(secrets,secret_file)
        secret_file.close()
    if not make_bootloader():
        print "ERROR: Failed to compile bootloader."
        sys.exit(1)
    bootFlash = genMem("flash.hex")
    bootFlash += b'\xff'*((8192) - len(bootFlash))
    if len(bootFlash) > 8192:
        bootFlash = bootFlash[:8192]
    # flashHash = CMACHash(secrets["H_KEY"],bootFlash)
    flashHash = CMACHash(secrets[2][1],bootFlash)
    with open('../bootloader/secret_build_output.txt', 'a') as secret_file:
        secret_file.write("#define flashHash \"" + bytesToCString(flashHash) + "\"\n")
        secret_file.close()
    write_fuse_file('lfuse', 0xE2)
    write_fuse_file('hfuse', 0xD8)
    write_fuse_file('efuse', 0xFC)
    write_fuse_file('lock', 0xFF)
    copy_artifacts()
