#!/usr/bin/env python
"""
Firmware Bundle-and-Protect Tool

"""
import argparse
import shutil
import struct
import json
import zlib

# Check the following file for byte manipulation functions
import byteManipulators

from cStringIO import StringIO
from intelhex import IntelHex

# This function takes a bytes object representing the HEX file
# and strips the appropriate data that nobody wants/needs.
# Returns a bytes object
def stripLine(intelLine):
    intLine = intelLine[3:][:4] + intelLine[:3][6:][:-2]
    return (int(intLine,16)).to_bytes(len(intLine),byteorder='big')

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Firmware Update Tool')

    parser.add_argument("--infile",
                        help="Path to the firmware image to protect.",
                        required=True)
    parser.add_argument("--outfile", help="Filename for the output firmware.",
                        required=True)
    parser.add_argument("--version", help="Version number of this firmware.",
                        required=True)
    parser.add_argument("--message", help="Release message for this firmware.",
                        required=True)
    args = parser.parse_args()

    # Parse Intel hex file.
    # firmware = IntelHex(args.infile)
    hexList = []
    with open(args.infile) hexFile:
        for line in hexFile:
            hexList.append(stripLine(line))
    b''.join(hexList)


    # Get version and size.
    firmware_size = firmware.maxaddr() + 1
    version = int(args.version)

    # Add release message to end of hex (null-terminated).
    sio = StringIO()
    firmware.putsz(firmware_size, (args.message + '\0'))
    firmware.write_hex_file(sio)
    hex_data = sio.getvalue()

    # Encode the data as json and write to outfile.
    data = {
        'firmware_size' : firmware_size,
        'version' : version,
        'hex_data' : hex_data
    }

    with open(args.outfile, 'wb+') as outfile:
        data = json.dumps(data)
        data = zlib.compress(data)
        outfile.write(data)

